# Generated by Django 4.0.2 on 2022-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='logo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
